export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REQUEST_HELP_SWITCH = "REQUEST_HELP_SWITCH";
export const REQUEST_HELP_SENT = "REQUEST_HELP_SENT";
export const ADD_FRIEND = "ADD_FRIEND";
export const SET_SOCKET = "SET_SOCKET";